### ISSUE TITLE
[Ranchers 2]NEW YORK CITY HAS TWO BUGS

### ISSUE THREAD

**Issue by TentFishColor** [tomwetjens/boardgamefiesta-app#11]
1. deliver to NEW YORK city can complete the SAN FRANCISICO Objective Card
2. NEW YORK city could be deliver more than once

**Comment by TentFishColor** [comment]
The rulebook of rails to the north, page 8 :
"Keep in mind that you still cannot deliver to the same city more than once. The only exceptions are still Kansas City and San Francisco. However, note that San Francisco is now located in the upper left part of the extension board. The last city on the city strip is now New York City, to which you can also only deliver once."

**Comment by tomwetjens** [comment]
Hmm interesting. Thanks, I did not know that.
Will make a change then :-)

**Comment by tomwetjens** [comment]
Fixed
